######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 6 21:12:32 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../projectData.h ../projectParams.h
SOURCES += main-test.cpp

QT +=  xml